- title: MinGine
  icon: ion-ios-cart-outline
  color: "#ff689b"
  url: /mingine
  description: >-
    クラウドサーバーでECサイトの構築と運営のサポートを低コストで導入できるシステムを提供しております。
    安全・安定・安心、１コインからECサイト運営できます。

#- title: Dolor Sitema
#  icon: ion-ios-bookmarks-outline
#  color: "#e9bf06"
#  url: "#"
#  description: >-
#    Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata

#- title: Sed ut perspiciatis
#  icon: ion-ios-paper-outline
#  color: "#3fcdc7"
#  url: "#"
#  description: >-
#    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur

#- title: Magni Dolores
#  icon: ion-ios-speedometer-outline
#  color: "#41cf2e"
#  url: "#"
#  description: >-
#    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum

#- title: Nemo Enim
#  icon: ion-ios-world-outline
#  color: "#d6ff22"
#  url: "#"
#  description: >-
#    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque

#- title: Eiusmod Tempor
#  icon: ion-ios-clock-outline
#  color: "#4680ff"
#  url: "#"
#  description: >-
#    Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi
